### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by skynet** [iicky/nflfanfare#1]
Are you planning to add documentation to the project. Thanks.

**Comment by iicky** [comment]
Thank you for your interest! I am still actively developing the project, so I haven't written full documentation for it as of yet. I started the project last year as a personal project, but ran into issues with matching the NFL plays to Twitter sentiment (it is nearly impossible to get the UTC time of NFL plays). I don't intend to release it as a Python package, but as a web application - most of the code is dependent on a MongoDB database on my server.

Are you more interested in the play information, or the sentiment analysis?

If you are interested in the plays, I would check out the nflgame and nfldb libraries by BurntSushi.

If you are interested in working with Twitter sentiment, the Twitter and Tweet classes are what I use to either scrape the Twitter mobile site or use the Twitter API to calculate game sentiment.

Feel free to contact me if you have any questions or are interested in the project. I'll send you the link when I get the web app up and running.

**Comment by skynet** [comment]
@iicky How's the web app coming along?
